# Site settings
title: Modern Web App Design Patterns
email: adamjbratt@gmail.com
description: > # this means to ignore newlines until "baseurl:"
	A catalog of design patterns for building modern web apps
baseurl: "/modern-design-patterns" # the subpath of your site, e.g. /blog/
url: "http://adambratt.github.io" # the base hostname & protocol for your site
twitter_username: bratt
github_username:  adambratt

# Build settings
markdown: kramdown
